import SportsEsportsIcon from "@mui/icons-material/SportsEsports";
import SportsBaseballIcon from "@mui/icons-material/SportsBaseball";
import ShowChartIcon from "@mui/icons-material/ShowChart";
import MonetizationOnIcon from "@mui/icons-material/MonetizationOn";
import PersonalVideoIcon from "@mui/icons-material/PersonalVideo";
import StarBorderPurple500Icon from "@mui/icons-material/StarBorderPurple500";
import MoreHorizIcon from "@mui/icons-material/MoreHoriz";
import KeyboardArrowDownRoundedIcon from "@mui/icons-material/KeyboardArrowDownRounded";

export const sidebarItems = [
  {
    id: 0,
    icon1: <SportsEsportsIcon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "Gaming",
    links: [
      "Valheim",
      "Genshin Impact",
      "Minecraft",
      "Pokimane",
      "Halo Infinite",
      "Call of Duty: Warzone",
      "Path of Exile",
      "Hollow Knight: Silksong",
      "Escape from Tarkov",
      "Watch Dogs: Legion",
    ],
  },
  {
    id: 1,
    icon1: <SportsBaseballIcon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "Sports",
    links: [
      "NFL",
      "NBA",
      "Megan Anderson",
      "Atlanta Hawks",
      "Los Angeles Lakers",
      "Boston Celtics",
      "Arsenal F.C.",
      "Philadelphia 76ers",
      "Premier League",
      "UFC",
    ],
  },
  {
    id: 2,
    icon1: <ShowChartIcon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "Business, Economics, and Finance",
    links: [
      "GameStop",
      "Moderna",
      "Pfizer",
      "Johnson & Johnson",
      "AstraZeneca",
      "Walgreens",
      "Best Buy",
      "Novavax",
      "SpaceX",
      "Tesla",
    ],
  },
  {
    id: 3,
    icon1: <MonetizationOnIcon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "Crypto",
    links: [
      "Cardano",
      "Dogecoin",
      "Algorand",
      "Bitcoin",
      "Litecoin",
      "Basic Attention Token",
      "Bitcoin Cash",
    ],
  },
  {
    id: 4,
    icon1: <PersonalVideoIcon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "Television",
    links: [
      "The Real Housewives of Atlanta",
      "The Bachelor",
      "Sister Wives",
      "90 Days Fiance",
      "Wife Swap",
      "The Amazing Race Australia",
      "Married at First Sight",
      "The Real Housewives of Dallas",
      "My 600-lb Life",
      "Last Week Tonight with John Oliver",
    ],
  },
  {
    id: 5,
    icon1: <StarBorderPurple500Icon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "Celebrity",
    links: [
      "Kim Kardashian",
      "Doja Cat",
      "Iggy Azalea",
      "Anya Taylor-Joy",
      "Jamie Lee Curtis",
      "Natalie Portman",
      "Henry Cavill",
      "Millie Bobby Brown",
      "Tom Hiddleston",
      "Keanu Reeves",
    ],
  },
  {
    id: 6,
    icon1: <MoreHorizIcon />,
    icon2: <KeyboardArrowDownRoundedIcon />,
    label: "More Topics",
    links: [
      "Animals and Pets",
      "Anime",
      "Art",
      "Cars and Motor Vehicles",
      "Crafts and DIY",
      "Culture, Race, and Ethnicity",
      "Ethics and Philosophy",
      "Fashion",
      "Food and Drink",
      "History",
      "Hobbies",
      "Law",
      "Learning and Education",
      "Military",
      "Movies",
      "Music",
      "Place",
      "Podcasts and Streamers",
      "Politics",
      "Programming",
      "Reading, Writing, and Literature",
      "Religion and Spirituality",
      "Science",
      "Tabletop Games",
      "Technology",
      "Travel",
    ],
  },
];
